// Generated by CoffeeScript 1.4.0
(function() {
  var canvasId, log10, sliderText;

  canvasId = "canvas";

  log10 = function(x) {
    return Math.log(x) / Math.LN10;
  };

  $blab.colorMap = {
    saturation: function(r) {
      return 1;
    },
    lightness: function(r) {
      return 0.5 * (1 - 1 / (1 + 25 * log10(2 * r + 1)));
    },
    opacity: function(r) {
      return 1 / (1 + 1 * log10(1 + 2 * r));
    }
  };

  sliderText = function(val) {
    return $("#slider_text").html("a=" + val);
  };

  $blab.complexFunction = function(spec) {
    var a, drawFunction, f, xMax;
    f = spec.f;
    xMax = spec.xMax;
    $(document).trigger("reprocessHtml");
    if (spec.a != null) {
      $("#slider").slider({
        min: spec.a.min,
        max: spec.a.max,
        step: spec.a.step,
        value: spec.a.init,
        slide: function(e, ui) {
          return sliderText(ui.value);
        },
        change: function(e, ui) {
          var a;
          a = ui.value;
          sliderText(a);
          return drawFunction(a);
        }
      });
    }
    drawFunction = function(a) {
      if (a != null) {
        f = function(z) {
          return spec.f(z, a);
        };
      }
      return new $blab.ComplexFunctionImage({
        f: f,
        xMax: xMax,
        canvasId: canvasId
      }, $blab.colorMap);
    };
    if (spec.a != null) {
      a = spec.a.init;
      sliderText(a);
      drawFunction(a);
    } else {
      drawFunction();
    }
    $("#mathjax").html("$f(z) = " + spec.mathJax + "$");
    return $(document).trigger("htmlOutputUpdated");
  };

}).call(this);
